# Generated by Django 5.2.5 on 2025-09-01 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='valid_until',
            new_name='expiry',
        ),
        migrations.RenameField(
            model_name='shorturl',
            old_name='long_url',
            new_name='url',
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='shortcode',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
